name: smart_real_estate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_locales: ^3.0.1

  # firebase
  firebase_core: ^2.29.0
  cloud_firestore: ^4.16.1
  #  firebase_auth: ^4.18.0
  firebase_storage: ^11.7.1
  #state management
  flutter_bloc: ^8.1.4
  #make request to api
  retrofit: ^4.1.0
  dio: ^5.4.1
  # json_annotation:
  json_annotation: ^4.8.1
  #cached image
  cached_network_image: ^3.2.0
  # svg imsges
  flutter_svg: ^2.0.9
  # for saving data
  shared_preferences: ^2.1.1
  # for bottom navigation
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  # for auto scroll widget
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  #comparing dart objects
  equatable: ^2.0.5
  #service locator
  get_it: ^7.6.7
  #dateFormat
  intl: ^0.18.0
  #Database
  floor: ^1.4.2
  #Photo view
  photo_view: ^0.14.0
  # Google Map
  google_maps_flutter: ^2.5.3

  path_icon: ^0.7.2


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.4
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6


flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/svg/
     - assets/locales/
     - assets/map/



  fonts:
     - family: Lato
       fonts:
         - asset: assets/fonts/Lato-Regular.ttf
