// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXRkqfT0LEYDtb_J-kD6CYAu3BnvRH70',
    appId: '1:673046587472:web:cca2b187cd096ec4690955',
    messagingSenderId: '673046587472',
    projectId: 'real-estate-app-ee644',
    authDomain: 'real-estate-app-ee644.firebaseapp.com',
    storageBucket: 'real-estate-app-ee644.appspot.com',
    measurementId: 'G-PFH7G0N1H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPwAgUmChsZjXxhWGle43BR9HipP7Yfug',
    appId: '1:673046587472:android:f6bb6da4bc5ea0f1690955',
    messagingSenderId: '673046587472',
    projectId: 'real-estate-app-ee644',
    storageBucket: 'real-estate-app-ee644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtD9Btgf61QpMhqP6UVxZ-HauhtmLrlZY',
    appId: '1:673046587472:ios:23b4ed85fd0eaa19690955',
    messagingSenderId: '673046587472',
    projectId: 'real-estate-app-ee644',
    storageBucket: 'real-estate-app-ee644.appspot.com',
    iosBundleId: 'com.example.smartRealEstate',
  );
}
